[workspace]
members = [
    "crates",
#    "examples/chess",
#    "examples/hex_map",
#    "examples/market",
#    "examples/matchmaker",
#    "examples/projectile",
    "token",
    "governance"
]

[workspace.package]
version = "0.7.2"
description = "Community-maintained libraries for Cairo"
homepage = "https://github.com/dojoengine/origami"
authors = ["bal7hazar@proton.me"]

[workspace.dependencies]
cubit = { git = "https://github.com/dojoengine/cubit", branch = "cairo_2.7" }
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v1.0.0-alpha.2" }
origami = { path = "crates" }
token = { path = "token" }
starknet = "2.7.0-rc.3"
