[package]
name = "origami"
version = "0.1.0"
homepage = "https://github.com/dojoengine/origami/tree/main/crates"

[dependencies]
cubit.workspace = true
starknet.workspace = true

[lib]

[tool.dojo.world]
seed = "origami"
namespace = { default = "origami" }
