[package]
name = "projectile"
version = "0.0.0"
description = "Example of algebria crate usage."
homepage = "https://github.com/dojoengine/origami/tree/examples/projectile"

[dependencies]
cubit.workspace = true
dojo.workspace = true
origami.workspace = true

[[target.dojo]]

[tool.dojo.world]
seed = "projectile"
namespace = { default = "projectile" }
